version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: vps
      POSTGRES_PASSWORD: "jLk_P-94TOrcL9mbLQp6X-gGmUurK7Dw"
    volumes:
      - vps_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "xMaMF6G27hUOBBZKDoYs7Ox0eNgUmlSp"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  vps_data:
