[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
    [entryPoints.websecure]
      address = ":443"
    [entryPoints.dbsecure]
      address = ":5432"
    [entryPoints.redis]
      address = ":6379"

[serversTransport]
  insecureSkipVerify = true

[api]
  dashboard = true

[certificatesResolvers.lets-encrypt.acme]
  email = "ssl@example.com"
  storage = "acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

[providers.docker]
  watch = true
  network = "web"

[providers.file]
  filename = "traefik_dynamic.toml"